# -*- coding: utf-8 -*-
"""AI_Music_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZ-YPDZOFFu164DDbFmnhUiNiastTVHN
"""

import os
import numpy as np
from music21 import stream, note, chord
print("Generating a stable, synthetic musical scale dataset...")
notes = []
scale_pitches = ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5']
for _ in range(50):
    for pitch in scale_pitches:
        notes.append(pitch)
    notes.extend(['0.4.7', '5.9.0', '2.5.9'])

print(f"Generated {len(notes)} valid musical elements safely in memory!")
sequence_length = 16
pitches = sorted(list(set(notes)))
vocab_size = len(pitches)
note_to_int = {note: i for i, note in enumerate(pitches)}
network_input = []
network_output = []
for i in range(len(notes) - sequence_length):
    seq_in = notes[i : i + sequence_length]
    seq_out = notes[i + sequence_length]
    network_input.append([note_to_int[char] for char in seq_in])
    network_output.append(note_to_int[seq_out])
n_patterns = len(network_input)
X = np.reshape(network_input, (n_patterns, sequence_length, 1)) / float(vocab_size)
from tensorflow.keras.utils import to_categorical
y = to_categorical(network_output, num_classes=vocab_size)
print(f"Data Prepared successfully. Shape of X: {X.shape}")
